# Schema for the configuration files of the group module.

group.settings:
  type: 'config_object'
  label: 'Group settings'
  mapping:
    use_admin_theme:
      type: 'boolean'
      label: 'Use admin theme when editing or creating groups'

group.type.*:
  type: 'config_entity'
  label: 'Group type'
  mapping:
    id:
      type: 'string'
      label: 'Machine-readable name'
    label:
      type: 'label'
      label: 'Label'
    description:
      type: 'text'
      label: 'Description'
    new_revision:
      type: 'boolean'
      label: 'Whether a new revision should be created by default'
    creator_membership:
      type: 'boolean'
      label: 'The group creator receives a membership'
    creator_wizard:
      type: 'boolean'
      label: 'The group creator must immediately complete their membership.'
    creator_roles:
      type: 'sequence'
      label: 'Group creator roles'
      sequence:
        type: 'string'
        label: 'Group role ID'

group_relation.config.group_cardinality:
  type: 'integer'
  label: 'Group cardinality'

group_relation.config.entity_cardinality:
  type: 'integer'
  label: 'Entity cardinality'

group_relation.config.use_creation_wizard:
  type: 'boolean'
  label: 'Use creation wizard'

# Follows the pattern group.role.GROUP_TYPE_ID-GROUP_ROLE_ID.
group.role.*:
  type: 'config_entity'
  label: 'Group role'
  mapping:
    id:
      type: 'string'
      label: 'Machine-readable name'
    label:
      type: 'label'
      label: 'Label'
    weight:
      type: 'integer'
      label: 'Weight'
    admin:
      type: 'boolean'
      label: 'Group role is an admin role'
    scope:
      type: 'string'
      label: 'The scope of the group role'
    global_role:
      type: 'string'
      label: 'The global role the group role synchronizes with. Only applies if scope is outsider or insider'
    group_type:
      type: 'string'
      label: 'Group type ID'
    permissions:
      type: 'sequence'
      label: 'Permissions'
      sequence:
        type: 'string'
        label: 'Group permission'

group_relationship_type:
  type: 'config_entity'
  label: 'Group relationship type'
  mapping:
    id:
      type: 'string'
      label: 'Machine-readable name'
    label:
      type: 'label'
      label: 'Label'
    description:
      type: 'text'
      label: 'Description'
    group_type:
      type: 'string'
      label: 'Group type ID'
    content_plugin:
      type: 'string'
      label: 'Group relation plugin ID'
    plugin_config:
      type: 'sequence'
      label: 'Plugin configuration'
      sequence:
        type: 'group_relation.config.[%key]'

# Follows the pattern group.relationship_type.GROUP_TYPE_ID-PLUGIN_ID.
# Follows the pattern group.relationship_type.GROUP_TYPE_ID-PLUGIN_ID-DERIVATIVE_ID.
group.relationship_type.*:
  type: 'group_relationship_type'
  label: 'Group relationship type'

entity_reference_selection.group_type:group_role:
  type: 'entity_reference_selection'
  mapping:
    group_type_id:
      type: 'string'
      label: 'The group type to check for available roles.'
