# Schema for the views plugins of the Group module.

views.access.group_permission:
  type: 'mapping'
  label: 'Group permission'
  mapping:
    group_permission:
      type: 'string'
      label: 'Group permission'

views.argument.group_id:
  type: views_argument
  label: 'Group ID'
  mapping:
    not:
      type: boolean
      label: 'Exclude'

views.argument_default.group_id_from_url:
  type: 'sequence'
  label: 'Group ID from current route'
  sequence:
    type: 'string'
    label: 'Group ID'

views_relationship_with_group_plugin_filter:
  type: 'views_relationship'
  mapping:
    group_relation_plugins:
      type: 'sequence'
      label: 'Group relation plugins'
      sequence:
        type: 'string'
        label: 'Group relation plugin ID'

views.relationship.group_relationship_to_entity:
  type: 'views_relationship_with_group_plugin_filter'
  label: 'Group relationship to entity reference'

views.relationship.group_relationship_to_entity_reverse:
  type: 'views_relationship_with_group_plugin_filter'
  label: 'Reverse group relationship to entity reference'

views.relationship.group_to_group_relationship:
  type: 'views_relationship_with_group_plugin_filter'
  label: 'Group to group relationship'
