wysiwyg_template.settings:
  type: config_object
  label: 'WYSIWYG template settings'
  mapping:
    library_path:
      type: path
      label: 'Root-relative path of the CKEditor Templates plugin directory'

wysiwyg_template.wysiwyg_template.*:
  type: config_entity
  label: 'WYSIWYG template'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'UUID'
    description:
      type: string
      label: 'Description'
    body:
      type: text_format
      label: 'The WYSIWYG template HTML'
    weight:
      type: integer
      label: 'Weight'
    node_types:
      type: sequence
      label: 'Available content types'
      sequence:
        type: string

node.type.*.third_party.wysiwyg_template:
  type: mapping
  label: 'Per content-type WYISIWYG template settings'
  mapping:
    default_template:
      label: 'Template to use for populating new content of this type'
      type: string
